apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: slack-subscription
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: slack
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: slack-integration
